In [24]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from tqdm import tqdm
import time
import pandas as pd
import numpy as np
import torch
import random
import matplotlib.pyplot as plt
import gzip as gz
import json
import pickle
from numpy import load

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

## rosetta?

In [25]:
clock_ids = set()
with gz.open('../data/rosetta/cells.json.gz', 'rt') as f:
    data = json.load(f)

for cell in data:
    if 'clk' in cell['name'].lower():
        print(cell)
        clock_ids.add(cell['id'])

{'name': 'sky130_fd_sc_hs__dlclkp_2', 'id': 111, 'width': 30720, 'height': 13320, 'terms': [{'name': 'GATE', 'id': 1, 'dir': 0, 'xloc': 1170, 'yloc': 1615}, {'name': 'GCLK', 'id': 2, 'dir': 1, 'xloc': 6970, 'yloc': 1710}, {'name': 'CLK', 'id': 3, 'dir': 0, 'xloc': 4885, 'yloc': 1612}, {'name': 'VGND', 'id': 4, 'dir': 2, 'xloc': 3840, 'yloc': 0}, {'name': 'VNB', 'id': 5, 'dir': 2, 'xloc': 3840, 'yloc': 122}, {'name': 'VPB', 'id': 6, 'dir': 2, 'xloc': 4368, 'yloc': 1961}, {'name': 'VPWR', 'id': 7, 'dir': 2, 'xloc': 3840, 'yloc': 3330}]}
{'name': 'sky130_fd_sc_hs__dlclkp_4', 'id': 112, 'width': 34560, 'height': 13320, 'terms': [{'name': 'GATE', 'id': 1, 'dir': 0, 'xloc': 1257, 'yloc': 1665}, {'name': 'GCLK', 'id': 2, 'dir': 1, 'xloc': 7605, 'yloc': 1554}, {'name': 'CLK', 'id': 3, 'dir': 0, 'xloc': 4735, 'yloc': 1570}, {'name': 'VGND', 'id': 4, 'dir': 2, 'xloc': 4320, 'yloc': 0}, {'name': 'VNB', 'id': 5, 'dir': 2, 'xloc': 4320, 'yloc': 122}, {'name': 'VPB', 'id': 6, 'dir': 2, 'xloc': 3373,

In [27]:

data = load(f'../data/rosetta/superblue1/superblue1_connectivity.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])
data

row
[478481 478482 478483 ... 797725 797725 738342]
col
[     0      0      0 ... 823022 823023 823023]
data
[3 3 3 ... 1 2 2]
shape
[797938 823024]


In [ ]:
print(clock_ids)

{266, 285, 286, 287, 288, 289, 290, 163, 164, 165, 166, 167, 301, 186, 315, 316, 317, 218, 111, 112, 113, 255}


In [ ]:
clk = []
for design in range(1,20):
    print(design)
    if design in [8,13,17]:
        continue
    with gz.open(f'../data/rosetta/superblue{design}/superblue{design}.json.gz', 'rt') as f:
        data = json.load(f)
    
    for instance in data['instances']:
        if instance['cell'] in clock_ids:
            print(instance)
            clk.append(instance)
        if 'clk' in instance['name'].lower():
            print(instance)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
with gz.open('../data/rosetta/superblue1/superblue1.json.gz', 'rt') as f:
    data = json.load(f)
data

{'instances': [{'name': 'o0',
   'id': 0,
   'xloc': 0,
   'yloc': 0,
   'cell': 132,
   'orient': 0},
  {'name': 'o1', 'id': 1, 'xloc': 0, 'yloc': 0, 'cell': 359, 'orient': 0},
  {'name': 'o10', 'id': 2, 'xloc': 0, 'yloc': 0, 'cell': 176, 'orient': 0},
  {'name': 'o100', 'id': 3, 'xloc': 0, 'yloc': 0, 'cell': 224, 'orient': 0},
  {'name': 'o1000', 'id': 4, 'xloc': 0, 'yloc': 0, 'cell': 360, 'orient': 0},
  {'name': 'o10000', 'id': 5, 'xloc': 0, 'yloc': 0, 'cell': 33, 'orient': 0},
  {'name': 'o100000', 'id': 6, 'xloc': 0, 'yloc': 0, 'cell': 346, 'orient': 0},
  {'name': 'o100001', 'id': 7, 'xloc': 0, 'yloc': 0, 'cell': 132, 'orient': 0},
  {'name': 'o100002', 'id': 8, 'xloc': 0, 'yloc': 0, 'cell': 224, 'orient': 0},
  {'name': 'o100003', 'id': 9, 'xloc': 0, 'yloc': 0, 'cell': 76, 'orient': 0},
  {'name': 'o100004',
   'id': 10,
   'xloc': 0,
   'yloc': 0,
   'cell': 237,
   'orient': 0},
  {'name': 'o100005',
   'id': 11,
   'xloc': 0,
   'yloc': 0,
   'cell': 183,
   'orient': 0},
  

In [ ]:
for d in data['instances']:
    if 'clk' in d['name']:
        print(d)

## pyg?

In [ ]:
file_path = "../data/superblue/superblue_1/pyg_data.pkl"

# Open and load the file
with open(file_path, 'rb') as file:  # 'rb' mode opens the file in binary read mode
    data = torch.load(file)

# Display the data
print(data.keys())
print(data)

['batch', 'pos_lst', 'net_hpwl', 'node_demand', 'edge_index_sink_to_net', 'edge_index_source_to_net', 'net_demand', 'num_vn', 'node_features', 'net_features']
Data(node_features=[797938, 45], net_features=[821523, 11], edge_index_sink_to_net=[2, 2139097], edge_index_source_to_net=[2, 810922], node_demand=[797938], net_demand=[821523], net_hpwl=[821523], batch=[797938], num_vn=99, pos_lst=[797938, 2])


In [ ]:
file_path = "../data/superblue/superblue_1/net_features.pkl"

# Open and load the file
with open(file_path, 'rb') as file:  # 'rb' mode opens the file in binary read mode
    data = pickle.load(file)

# Display the data
print(data.keys())
print(data['instance_features'])

dict_keys(['instance_features'])
[[9.8392700e+05 2.6645090e+02 0.0000000e+00 ... 2.2582787e-01
  4.5752829e-01 8.8919508e-01]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0000000e+00]
 ...
 [3.6200000e+02 3.3983008e-03 0.0000000e+00 ... 4.3945628e-01
  6.1541706e-01 7.8820163e-01]
 [1.2000000e+01 3.1984008e-03 0.0000000e+00 ... 4.0544713e-01
  5.9458333e-01 8.0403399e-01]
 [3.6200000e+02 3.3983008e-03 0.0000000e+00 ... 4.6288991e-01
  6.2907302e-01 7.7734619e-01]]


## raw

In [ ]:
file_path = "../data/2023-03-06_data/0.net_features.pkl"

# Open and load the file
with open(file_path, 'rb') as file:  # 'rb' mode opens the file in binary read mode
    data = pickle.load(file)

# Display the data
print(data.keys())
#print(data)
print(data['instance_features'])

dict_keys(['instance_features'])
[[9.8392700e+05 2.6645090e+02 0.0000000e+00 ... 3.5756442e-01
  5.6296331e-01 8.2648188e-01]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.0000000e+00]
 ...
 [3.6200000e+02 3.3983008e-03 0.0000000e+00 ... 4.9161056e-01
  6.4509642e-01 7.6410115e-01]
 [1.2000000e+01 3.1984008e-03 0.0000000e+00 ... 5.2437568e-01
  6.6248989e-01 7.4907082e-01]
 [3.6200000e+02 3.3983008e-03 0.0000000e+00 ... 4.7562426e-01
  6.3627118e-01 7.7146548e-01]]


In [ ]:
file_path = "../data/2023-03-06_data/0.node_features.pkl"

# Open and load the file
with open(file_path, 'rb') as file:  # 'rb' mode opens the file in binary read mode
    data = pickle.load(file)

# Display the data
print(data.keys())
#print(data['instance_features'])

dict_keys(['num_instances', 'num_nets', 'x_min', 'x_max', 'y_min', 'y_max', 'min_cell_width', 'max_cell_width', 'min_cell_height', 'max_cell_height', 'instance_features', 'sample_name', 'folder', 'design'])
